import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';

import { db } from './client';
// Generated by `npx drizzle-kit generate` from db/schema.ts — do not hand-edit.
import migrations from './migrations/migrations';

/** Runs pending SQL migrations against the on-device DB; call once from the root layout. */
export function useDatabaseMigrations() {
  return useMigrations(db, migrations);
}
